### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'loginctl'

### ISSUE THREAD

**Issue by francoism90** [flathub/org.bleachbit.BleachBit#13]
```
$ flatpak run org.bleachbit.BleachBit 
Traceback (most recent call last):
  File "/app/bin/bleachbit", line 40, in <module>
    bleachbit.Unix.is_display_protocol_wayland_and_root_not_allowed()
  File "/app/share/bleachbit/Unix.py", line 746, in is_display_protocol_wayland_and_root_not_allowed
    bleachbit.Unix.is_linux_display_protocol_wayland() and
  File "/app/share/bleachbit/Unix.py", line 731, in is_linux_display_protocol_wayland
    result = General.run_external(['loginctl'])
  File "/app/share/bleachbit/General.py", line 147, in run_external
    p = subprocess.Popen(args, stdout=stdout,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'loginctl'
```
This happens after upgrading to latest version.

I tried resetting permissions, and removing the stored data.

Thanks

**Comment by francoism90** [comment]
@proletarius101 If I understand correctly, it should ask for my root password?

**Comment by francoism90** [comment]
@proletarius101 No, I just though it needed to run as root. :)

I'll try the test build.
